# Generated by Django 3.1.5 on 2021-02-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50)),
                ('user', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
