# Generated by Django 3.1.5 on 2021-02-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='user',
            field=models.IntegerField(null=True),
        ),
    ]
